[package]
name = "scope-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/huacnlee/zed.git", branch = "export-platform-window", default-features = false, features = ["http_client", "font-kit"] }
tokio = "1.41.1"
